stages:
  - build
  - test

b:reactor:test:
  stage: build
  services:
    - name: docker:dind
      command: ["--insecure-registry", "git-man-dev.nccgroup.local:4461"]
  only:
    - merge_requests
    - qat
    - uat
    - master
  tags:
    - docker-build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -f Dockerfile-test -t ${CI_REGISTRY_IMAGE}/reactor:test .
    - docker push ${CI_REGISTRY_IMAGE}/reactor:test


t:unit:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/reactor:test
  dependencies:
    - b:reactor:test
  script:
    - py.test

t:integration:5.6.16:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/reactor:test
  dependencies:
    - b:reactor:test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Elogger.level=error"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh

t:integration:6.3.0:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/reactor:test
  dependencies:
    - b:reactor:test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Elogger.level=error"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh

t:integration:6.8.2:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/reactor:test
  dependencies:
    - b:reactor:test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Elogger.level=error"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh

t:integration:7.3.0:
  stage: test
  image: ${CI_REGISTRY_IMAGE}/reactor:test
  dependencies:
    - b:reactor:test
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Elogger.level=error", "-Enode.name=elasticsearch", "-Ediscovery.seed_hosts=elasticsearch", "-Ecluster.initial_master_nodes=elasticsearch"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh