stages:
  - test

t:unit:
  stage: test
  image: python:latest
  before_script:
    - pip install -r requirements-dev.txt -r requirements.txt
    - python setup.py install
    - python install -e .
  script:
    - py.test

t:integration:5.6.16:
  stage: test
  image: python:latest
  before_script:
    - pip install -r requirements-dev.txt -r requirements.txt
    - python setup.py install
    - python install -e .
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      alias: elasticsearch
      command: ["-Elogger.level=error"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh

t:integration:6.3.0:
  stage: test
  image: python:latest
  before_script:
    - pip install -r requirements-dev.txt -r requirements.txt
    - python setup.py install
    - python install -e .
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      alias: elasticsearch
      command: ["-Elogger.level=error"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh

t:integration:6.8.2:
  stage: test
  image: python:latest
  before_script:
    - pip install -r requirements-dev.txt -r requirements.txt
    - python setup.py install
    - python install -e .
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      alias: elasticsearch
      command: ["-Elogger.level=error"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh

t:integration:7.3.0:
  stage: test
  image: python:latest
  before_script:
    - pip install -r requirements-dev.txt -r requirements.txt
    - python setup.py install
    - python install -e .
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      alias: elasticsearch
      command: ["-Elogger.level=error", "-Enode.name=elasticsearch", "-Ediscovery.seed_hosts=elasticsearch", "-Ecluster.initial_master_nodes=elasticsearch"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - ./tests/integration/test.sh