stages:
  - build
  - test
  - deploy

image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "${CI_PROJECT_ID}_${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/pip
    - venv/
  policy: pull

before_script:
  - python -V
  - mv .pypirc ~/.pypirc
  - pip install --upgrade virtualenv
  - virtualenv venv --always-copy
  - source venv/bin/activate

  # Test template
.cache_template:
  tags:
    - code
  only:
    - merge_requests


b:reactor:
  extends: .cache_template
  stage: build
  script:
    - pip install -r requirements.txt -e .
  # Override the cache definition to write to it
  cache:
    key: "${CI_PROJECT_ID}_${CI_COMMIT_REF_SLUG}"
    paths:
      - .cache/pip
      - venv/
    policy: push


t:unit:
  extends: .cache_template
  stage: test
  dependencies:
    - b:reactor
  script:
    - pip install -r requirements.txt -r requirements-dev.txt
    - py.test

t:integration:5.6.16:
  extends: .cache_template
  stage: test
  except:
    refs:
      - /(^|\/)feature\/.*$/
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP/
  dependencies:
    - b:reactor
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
      alias: elasticsearch
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - pip install -r requirements.txt -e .
    - ./tests/integration/test.sh

t:integration:6.3.0:
  extends: .cache_template
  stage: test
  except:
    refs:
      - /(^|\/)feature\/.*$/
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP/
  dependencies:
      - b:reactor
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
      alias: elasticsearch
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - pip install -r requirements.txt -e .
    - ./tests/integration/test.sh

t:integration:6.8.2:
  extends: .cache_template
  stage: test
  except:
    refs:
      - /(^|\/)feature\/.*$/
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP/
  dependencies:
    - b:reactor
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
      alias: elasticsearch
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - pip install -r requirements.txt -e .
    - ./tests/integration/test.sh

t:integration:7.3.0:
  extends: .cache_template
  stage: test
  except:
    refs:
      - /(^|\/)feature\/.*$/
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^WIP/
  dependencies:
    - b:reactor
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Enode.name=elasticsearch", "-Ediscovery.seed_hosts=elasticsearch", "-Ecluster.initial_master_nodes=elasticsearch"]
  variables:
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  script:
    - pip install -r requirements.txt -e .
    - ./tests/integration/test.sh



d:docs:
  stage: deploy
  only:
    - tags
  script:
    - pip install -r requirements-docs.txt -e .
    - cd docs
    - sphinx-build -b html -d build/doctrees -W source build/html
  artifacts:
    paths:
    - docs/build/html/**

d:publish:
  stage: deploy
  only:
    - tags
  before_script:
    - python -V
    - mv .pypirc ~/.pypirc
    - pip install --upgrade virtualenv
    - virtualenv venv --always-copy
    - source venv/bin/activate
    - pip install --upgrade setuptools wheel
    - pip install --upgrade twine
  script:
    - python3 setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload -r ncc dist/* --verbose --cert /etc/ssl/certs/ca-certificates.crt
