version: '3.3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: reactor_test_elasticsearch
    environment:
      # Hide the normal logging for the test
      - logger.level=error
      # >= v7.x.x settings for establishing the cluster
#      - node.name=elasticsearch
#      - discovery.seed_hosts=elasticsearch
#      - cluster.initial_master_nodes=elasticsearch
      # Increase base memory limits (JVM)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  reactor:
    build:
      context: ""
      dockerfile: ./Dockerfile-test
    command: /home/reactor/tests/integration/test.sh
    container_name: reactor_test
    working_dir: /home/reactor
    volumes:
      - ./:/home/reactor/
      - ./tests/integration/:/home/reactor/tests/integration/
    depends_on:
      - elasticsearch