---
$schema: http://json-schema.org/draft-07/schema#
title: "Reactor Client"

definitions: {}

type: object
required: [elasticsearch]

properties:
  index:
    type: string
    title: "Writeback index (index prefix for ElasticSearch >= 6.x"
    default: "reactor"
  alert_alias:
    type: string
    title: "Alias for all alert indices"
    default: "reactor_alerts"
  writeback_flush:
    type: integer
    title: "Maximum number of writeback actions to cache before flushing"
    default: 1000
  max_processpool:
    type: integer
    title: "Maximum number of processes to run rules in (capped between 1 and CPU count)"
    default: 0


  alert_time_limit:
    default: {days: 2}
    allOf:
      - $ref: "common.yaml#/definitions/timeframe"
  old_query_limit:
    default: {weeks: 1}
    allOf:
      - $ref: "common.yaml#/definitions/timeframe"
  max_aggregation:
    default: 10000
    type: integer
  string_multi_field_name:
    default: ~
    type: [string, 'null']

  reload:
    default: {seconds: 3}
    allOf:
      - {$ref: "common.yaml#/definitions/timeframe"}
  resend:
    default: {seconds: 30}
    allOf:
      - {$ref: "common.yaml#/definitions/timeframe"}

  elasticsearch: {$ref: 'file:common.yaml#/definitions/elasticsearch'}


  loader:
    type: object
    default: {}
    additionalProperties: false
    properties:
      type:
        type: [string, 'null']
        title: "Loader type (either a mapping or `package.module.ClassName`)"
        default: file
        examples:
          - file
          - package.module.ClassName

      config:
        type: object
        title: "Configuration for the loader"
        default: {}

  rule:
    type: object
    title: "Default rule configurations (applied to all rules)"
    default: {}

    properties:
      max_query_size:
        type: integer
        title: "Maximum size of results returned by a single query"
        default: 10000
        maximum: 10000
        minimum: 1
      scroll_keepalive:
        type: string
        title: ""
        default: "30s"
      disable_rule_on_error:
        type: boolean
        title: "Whether to disable a rule if it raises an exception"
        default: true
      buffer_time: {$ref: "common.yaml#/definitions/timeframe"}
      run_every: {$ref: "common.yaml#/definitions/timeframe"}
      _source_enabled:
        default: True
        type: boolean




  mappings:
    type: object
    title: "Set of user friendly mappings for alerters, loaders, and rule types"
    default: {}
    additionalProperties: false
    properties:
      alerter:
        title: "Lookup dictionary of human name to Alerter"
        type: object
        default: {}
        additionalProperties:
          type: string

      enhancement:
        title: "Lookup dictionary of human name to Enhancement"
        type: object
        default: {}
        additionalProperties:
          type: string

      loader:
        title: "Lookup dictionary of human name to RuleLoader"
        type: object
        default: {}
        additionalProperties:
          type: string

      ruletype:
        title: "Lookup dictionary of human name to Rule"
        type: object
        default: {}
        additionalProperties:
          type: string
...
